language: node_js
sudo: false
node_js:
  - "node"
services:
  - postgresql
install:
  - "npm install"
before_script:
  - psql -c 'create database users_test;' -U postgres
  - psql -c "CREATE USER ivan WITH PASSWORD '123456';" -U postgres
script:
  - "npm test"